#!/usr/bin/python
# -*- coding: utf-8 -*-

def algoritmos():
	print(" ===========================================================================")
	print("|            ALGORITMOS CRIPTOGRAFICOS                                      |")
	print("|        SINTAXIS: python3 Main.py <algoritmo>                              |")
	print("| <Algoritmo>:                                                              |")
	print("|              -jc Algoritmo Julio Cesar                                    |")
	print("|              -af Algoritmo Criptoanalisis de frecuencia                   |")
	print("|              -pb Algoritmo Polybios                                       |")
	print("|              -at Algoritmo Atbash                                         |")
	print(" ===========================================================================")
	print("Consultar la ayuda de un algoritmo:")
	print("                         	SINTAXIS:")
	print("                                      python3 Main.py <algoritmo>")
def ayudacesar():
	print(" ==================================================================================")
	print("|               ALGORITMO  JULIO CESAR                                             |")
	print("| SINTAXIS: python3 Main.py -jc <modo> <ArchivoEntrada.txt>  <Clave>               |")
	print("| <ArchivoEntrada.txt>: Nombre del archivo de entrada                              |")
	print("| <modo>                                                                           |")
	print("| -c : Parametro para cifrar                                                       |")
	print("| -d : Parametro para descifrar                                                    |")
	print("| <Clave> : Clave para cifrar o Descifrar                                          |")
	print("| Ejemplos:                                                                        |")
	print("|          python3 Main.py -jc -c quijote.txt 3                                    |")
	print("| Elaborado Por:  Davinson Mellizo                                                 |")
	print("| Correo: davinsonmellizo@unicauca.edu.co                                          |")
	print("| Fecha de Creación: 22/09/2018                                                    |")
	print("| Materia: Introducciòn a la Criptografìa                                          |")
	print("| Profesor: Siler Amador Donado                                                    |")
	print(" ==================================================================================")
def ayudaAtbash():
	print(" ==================================================================================")
	print("|                       ALGORITMO ATBASH                                           |")
	print("| SINTAXIS: python3 Main.py -at <modo> <ArchivoEntrada.txt>                        |")
	print("| <ArchivoEntrada.txt>: Nombre del archivo de entrada                              |")
	print("| <modo>                                                                           |")
	print("| -c : Parametro para cifrar                                                       |")
	print("| -d : Parametro para descifrar                                                    |")
	print("| Ejemplos:                                                                        |")
	print("|          python3 Main.py -at -c quijote.txt                                      |")
	print("| Elaborado Por:  Davinson Mellizo                                                 |")
	print("| Correo: davinsonmellizo@unicauca.edu.co                                          |")
	print("| Fecha de Creación: 22/09/2018                                                    |")
	print("| Materia: Introducciòn a la Criptografìa                                          |")
	print("| Profesor: Siler Amador Donado                                                    |")
	print(" ==================================================================================")

def ayudaFrecuencia():
	print(" ==================================================================================")
	print("|               ALGORITMO  ANALISIS POR FRECUENCIA                                 |")
	print("| SINTAXIS: python3 Main.py -af <ArchivoEntrada.txt>                               |")
	print("| <ArchivoEntrada.txt>: Nombre del archivo de entrada                              |")
	print("| Ejemplos:                                                                        |")
	print("|          python3 Main.py -af quijote.txt quijoteDescifrado.txt                   |")
	print("| Elaborado Por:  Davinson Mellizo                                                 |")
	print("| Correo: davinsonmellizo@unicauca.edu.co                                          |")
	print("| Fecha de Creación: 22/09/2018                                                    |")
	print("| Materia: Introducciòn a la Criptografìa                                          |")
	print("| Profesor: Siler Amador Donado                                                    |")
	print(" ==================================================================================")

def ayudapolybios():
	print(" =============================================================================================")
	print("|               ALGORITMO POLYBIOS                                                            |")
	print("| SINTAXIS: python3 Main.py -pb <modo> <alfabeto> <ArchivoEntrada.txt>                        |")
	print("| <ArchivoEntrada.txt>: Nombre del archivo de entrada                                         |")
	print("| <ArchivoSalida.txt>: Nombre del archivo de salida                                           |")
	print("| <modo>                                                                                      |")
	print("| -c : Parametro para cifrar                                                                  |")
	print("| -d : Parametro para descifrar                                                               |")
	print("| <alfabeto>                                                                                  |")
	print("| -l : Parametro para cifrar con letras                                                       |") 
	print("| -n : Parametro para cifrar con numeros                                                      |")
	print("| Ejemplos:                                                                                   |")
	print("|          python3 Main.py -pb -c -l quijote.txt                                          |")
	print("| Elaborado Por:  Davinson Mellizo                                                            |")
	print("| Correo: davinsonmellizo@unicauca.edu.co                                                     |")
	print("| Fecha de Creación: 22/09/2018                                                               |")
	print("| Materia: Introducciòn a la Criptografìa                                                     |")
	print("| Profesor: Siler Amador Donado                                                               |")
	print(" =============================================================================================")

def fin():
	print("================================================")
	print()
	print("OPERACION TERMINADA CON EXITO!!!")
	print()
	print("================================================")
def resultadoCIF():
	print("================================================")
	print("!!!Resultado en Resultado.CIF!!!")
	print("================================================")
def resultadoDEC():
	print("================================================")
	print("!!!Resultado en Resultado.DEC!!!")
	print("================================================")
	
    
